server:
  port: 8081

logging:
  level:
    fr.acle: DEBUG
    org.springframework: DEBUG


notello:
  endpoints:
    note: http://localhost:8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://aclement.au.auth0.com/